#+TITLE: 
#+Author: Hjalte Søberg Mikkelsen
#+Date: 
#+EMAIL: hjalte.soeberg.mikkelsen@regionh.dk
#+LaTeX_CLASS: org-article 
#+OPTIONS: toc:nil
#+LaTeX_HEADER:\usepackage{authblk}
#+LaTeX_HEADER:\author{Hjalte Søberg Mikkelsen}
#+LaTeX_HEADER:\affil{Steno Diabetes Center Copenhagen}
#+setupfile:~/emacs-genome/snps/org-templates/setup-all-purpose.org
# #+superman-org-export-target: pdf
#+bibliography: bibliography.bib
#+LATEX_HEADER: \bibliographystyle{plainnat}


\newpage
* DP-next

My PhD project is part of a larger project called DP-next. DP-Next is
a project aimed at developing a sustainably effective strategy for
prevention of Type 2 Diabetes in Denmark, Greenland and the Faroe
Islands. The project has been funded by a Steno National Collaborative
Grant from the Novo Nordisk Foundation and the full name of the
project is: Sustainable Type 2 Diabetes Prevention for the 21st
Century. The project is called DP-Next because we intend to develop
the next generation of Diabetes Prevention strategies. The DP-Next
project consists of four work packages: WP1 (Management and
Collaboration), WP2 (Risk Prediction), WP3 (Heterogeneity), WP4
(Intervention Development). My PhD project falls under WP2 of the
DP-Next project. In collaboration with the DP-Next teams I will work
on the statistial methods for a register-based diabetes risk
prediction model for the entire Danish, Greenlandic and Faroese
populations. Furthermore, my PhD project work is connected with WP4
where we will in collaboration derive subgroups based on heterogeneity
in T2D risk.

* My Project

My project aims to develop and adapt statistical methodology to create
a super learner algorithm which produces diabetes risk prediction
models based on registry data. In collaboration with the research team
of WP2, the algorithm will be applied to build models for the Danish,
the Faroese and the Greenlandic populations. Specifically, I will
apply the algorithm to build and validate a type 2 diabetes risk prediction
model for the Danish population such that the model has the following
features:

- Exclusively use register-based data such that the prediction model
  can be calculated for the entire population of Denmark, without the
  need to ask individuals for additional information.
- Is designed for yearly updates based on newly available / updated
  risk indicator data.
- Can incorporate longitudinal data (risk factor trajectories)
- Can incorporate time-dynamic risk indicators from family members

In collaboration with the research team of WP4 I will also develop
statistical methods that can identify subgroups of the population with
high type 2 diabetes risk. To achieve these overarching goals for the DP-next
project, my PhD work is divided in the following three sub-projects.

** COMMENT Project 1: Identifying sub-groups with high diabetes risk
# 1. Motivation (please add something about WP4 and say risk of diabetes instead of risk)
WP4 of the DP-next project aims to develop intervention strategies for prevention of T2D targeted on subgroups of the danish population, who has high risk of T2D. These high risk subgroups will be identified in this project. I will in this project aim to extend current methodology in sub-group
analysis such that I can identify population subgroups with a high risk of T2D, using an
existing risk prediction model.

# 2. State-of-the art (Start with a more classic reference perhaps? Lets discuss this)
Traditional subgroup analysis methods compares predefined subgroups with eachother, to find f. eks. the highest risk subgroup or subgroups with highest treatment effect. A big drawbag to these methods is 

[cite:@SDmapSubgroup] presents the novel SD-Map algorithm for exhaustive
but efficient subgroup discovery. SD-Map guarantees to identify all interesting
subgroup patterns contained in a data set, in contrast to heuristic or sampling-
based methods.

[cite:@subgrouptree] Introduced regression tree–based subgroup discovery for treatment heterogeneity — bridge between ML and statistics.

[cite:@datadrivensubgroup] Unified statistical and ML subgroup methods; introduced validation and stability analysis. (for clinical trials)

One current method in the field is [cite:@guo2023], who finds the
highest risk sub-group by pre-specifying either two or six sub-groups,
fitting a logistic regression model and then using a bootstrap
inspired algorithm. This method attains a low biased estimate with
tight confidence intervals. This framework needs to be extended such
that it can identify multiple high risk sub-groups among any number of
sub-groups and use an already fitted risk prediction model instead of
fitting a logistic regression model. Another method is shown in
[cite:@parikh2021], which uses an existing risk prediction model and
clustering methods on the covariates to identify subgroups of
high-risk. Clustering methods are however very sensitive and may not
be suitable for our registry data due to size [cite:@wani2024], so a
different method needs to be considered to identify the subgroups.

# 3. Work plan (better to have a bad plan than no plan ;)
The methodology developed in this project will be used to identify the
sub-groups in the Danish population with the highest risk of
developing type 2 diabetes.

*** COMMENT Potential methods and thoughts
In motivation talk more about the real world problems and what DP-next wants.
Talk to the people from wp4 to know exactly what they want (should groups be pre-defined, should risk treshold be pre-defined, how many people should be in the groups).
Maybe write the problem up mathematically

Thomas does the following:
- Use the model on all individuals
- Only look at the people with a risk greater than $\xi$ (some number)
- Cluster people into groups based on covariates and make the clusters change size based on covariates reprensentitivenes (how often we see that specific covariate value in the population.




** Project 2: Joint inference of cause-spceific cumulative incidence functions (Constrained risk prediction)
# Notes
# Talk more about the practical problem and then lead that into the theoretical problem

# Practical problem: Assume we observe two people - person 1 has a hba1c of 53 and person 2 has hba1c of 53 but has end stage brain cancer. Person 1 will have a larger risk of getting T2D than person 2 even though they have the same hba1c level, because the risk of person 2 dying is way higher than person 1. Therefore we need to report both the risk of T2D and the risk of dying, for the risk prediction to make sense. When estimating these cause specific risks in practise in can happen that person 2 has a risk of T2D of 53% and a risk of dying of 60%, i.e. the total sum of risks is over 100%. We therefore need some framework that ensures that $S = 1-F_1-F_2$ where S is the event free survival function, and F 1 and 2 are the cause specific cumulative incidence functions.

# Motivation
When using the type 2 diabetes (T2D) risk prediction model, it is essential to accurately report both the risk of T2D and the risk of death. This is because, when investigating heterogeneity in T2D risk across the population, it is necessary to account for the competing risk of death, which directly influences the estimated T2D risk. For example, if two individuals have similar covariates but one has end-stage brain cancer, that individual will have a lower estimated risk of T2D solely due to an increased risk of death. Reporting both competing risks is also important for potential clinical applications: an individual with a high risk of death should not be targeted for preventive intervention based solely on an elevated T2D risk.

When estimating cause-specific risks parametricly in a time-to-event setting, we typically aim to estimate the cause-specific hazards or the cause specific cumulative incidence functions (CIFs). A common issue for these types of models is that the total estimated risk can exceed 1 [cite:@fine]. Specifically, I aim to estimate the cause-specific CIFs for T2D and death, denoted as $F_{T2D}$ and $F_{death}$, respectively. In practise, it is possible that $F_{T2D}+F_{death}>1$ which implies that $S\neq 1-(F_{T2D}+F_{death})$, where $S$ is the event free survival function. This typically occurs for covariate patterns that fall outside the range of those observed in the training data. Therefore, it is necessary to develop a modeling framework that enforces the constraint $S = 1-(F_{T2D}+F_{death})$ (or equivalently $F_{T2D}+F_{death}\leq 1$) holds for all covariate values.

# Current methods
This problem arises because the cause-specific hazards are estimated separately for each cause, rather than jointly under the constraint described above. The issue has been studied previously, and a potential solution was proposed by [cite:@li2016]. However, that solution was developed only for the Cox proportional hazards model and has not been extended to other modeling frameworks.

# Work plan
In this project, I aim to generalize this approach to a broader class of models, thereby establishing a unified framework applicable to all models that estimate either cause-specific hazards or cause-specific CIFs. I will then implement this framework within a Super Learner algorithm [cite:@super], designed to produce the best-performing T2D risk prediction model from an ensemble of parametric and machine learning models. This new constrained risk prediction framework will provide the core parametric components of the Super Learner. Ultimately, the resulting model will use Danish registry data to predict the 5- and 10-year risk of developing type 2 diabetes.


** Project 3: Large-Language-Models in risk prediction
# The methods described also needs to be more precise (it has to make sense reading it in 2 years)

# Motivation
To build the most accurate risk prediction model for T2D, it is essential to incorporate all available data. However, this is not a straightforward task, as the Danish registry data used in this project are longitudinal, and the interpretation of missingness varies across registries. Two of the registries used in this project are the Danish National Prescription Registry (LMDB) and the Register of Laboratory Results for Research (RLRR).
In the LMDB, a missing observation indicates that an individual was not prescribed any drugs. In contrast, in the RLRR, a missing observation does not imply that the individual lacks biomarker data—it merely indicates that no laboratory measurements were recorded during that period. Furthermore, the time points of measurements differ from person to person. For example, if we wish to examine the most recent measurement of a covariate X before time 0, the last measurement for person 1 might be $X(0 - t)$, where $t=1$ day, whereas for person 2 it could be $X(0-s)$, with $s\neq t$ . This pattern is typical for most, if not all, covariates in the registries.

Such data structures are impossible to incorporate into traditional likelihood-based risk prediction frameworks. Consequently, new methodological approaches are required to fully utilize the richness of the registry data.
\newline

# Current methods
To address this challenge, recent studies have proposed the use of machine learning methods, in particular Neural Networks. [cite:@dynamicdeephit] build the Dynamic-DeepHit model that can incorporate longitudinal data measured at irregular timepoints to estimate the cause-specific cumulative incidence functions. However, it remains unclear how the model handles missing data or scales to large registry datasets. A similar approach was taken by [cite:@wright2021], who employed recurrent neural networks (RNNs) to efficiently incorporate covariate histories into a risk prediction model, where the model was trained danish registry data. A natural extension of these methods is to use Transformers instead of RNNs, which have the advantage of better handling large datasets and longitudinal data with long histories [cite:@attention]. Using Transformers will make the framework similar to that of large language models (LLMs), which recently have been used for disease risk prediction by [cite:@delphi], who proposed a modified GPT-based model to predict the risk of over 1,000 diseases using data from the UK Biobank.

# Work plan
In this project, I will develop a large language model for T2D risk prediction, following a similar approach to [cite:@delphi]. Specifically, I will train a modified GPT-based model on Danish registry data to predict T2D risk exclusively. If this proves too challenging — given that this is a relatively unexplored area — I will instead employ methods similar to those proposed by [cite:@dynamicdeephit] and [cite:@wright2021].

The resulting model will be incorporated into the super learner algorithm developed in Project 2, contributing to the creation of the best-performing T2D risk prediction model for the Danish population.

# Maybe describe a backup method


** Data
The model will be developed using synthetic data following the
structure of the Danish register-data. All analyses will be conducted
on a DST project database and transferred/validated in both real
Danish register data, and in Greenlandic and Faroese data. Using
register data available on DST, the type 2 diabetes outcome will be
defined according to a previously validated classification
[cite:@isaksen2023validation]. The analyses using Danish register data
will be conducted on the DST project databyase at Steno Diabetes
Center Aarhus, incorporating a wide range of data sources for model
development, including the Danish Diabetes Database and several other
health and socio-demographic registers.

# HJALTE: I think that much of comes below is only marginally relevant for your phd protocol
# and the relevant part needs to be integrated into the 3 projects above. do you agree?

* COMMENT WP2

It is well known that type 2 diabetes (T2D) in trial settings can be prevented in high-risk individuals
through intensive lifestyle modifications. However, translating these findings into sustainable,
real-world practices has proved difficult. The original interventions were too resource-intensive for
large-scale use, while less intensive approaches only produced temporary weight loss without long-term
diabetes prevention. Additionally, many of the highest at-risk groups are rarely identified in routine
care, and participation in health promoting programs among these groups has declined. Despite these
challenges, new opportunities for diabetes prevention have emerged, including advanced health data
systems, machine learning, better understanding of behavior change, innovative intervention methods,
real-time monitoring technologies, and widespread use of apps and smartphones. These resources remain
underutilized but hold great potential to improve prevention strategies.

** Aim
The aim of WP2 is to develop an operational risk model that calculates an individual diabetes risk
prediction for the entire population of Denmark, Greenland and the Faroe Islands. We will achieve this
by designing a risk prediction algorithm based exclusively on existing register-based data. WP2 will
have a duration of 3 years (Years 1 to 3 of the project) and includes partners from all 7 Steno Centres.

** General Objectives
WP2 has objectives at the level of:
1. The total population
2. Population subgroups
3. Individuals
4. The Health system

In Denmark, the first two sets of objectives will be executed based on register data (DST environment),
while the third and fourth sets will require transfer of models and working environments to operational
electronic medical record (EMR) databases in at least one Danish Region. Data analysis in Greenland and
the Faroe Islands will be carried out in parallel, in separate data environments using data from the
local EMR systems. Components and partial models may be transferred between the three participating
countries.

*** Total Population level
Descriptive epidemiology of diabetes and diabetes risk: Once a suitable risk prediction model has been
established, the objective is to use it to describe the state and temporal development of diabetes risk
in Denmark, Greenland and the Faroe Islands. This analysis can include subdivisions at the level of
regions/municipalities. It can furthermore include an analysis of the relative contribution of broad
groups of risk factors to the state and trends in diabetes risk. Once the analysis protocol for this
descriptive aim has been fully developed, applied and published in a peer-reviewed journal, updated
analyses can be calculated on a yearly basis and the results can be made public as updates on the
DP-Next project website.

*** Population subgroups
Within each of the three target countries, the risk prediction model will be used for the
identification of subgroups at high diabetes risk. The objective is to identify among individuals
with high diabetes risk groups of people with different clustered combinations of contributing risk
indicators. In a hypothetical example, women aged over 50 with two first-degree relatives with diabetes
may have a an equivalent absolute diabetes risk to non-participants in national screening programs with
low socio-economic status or to men aged over 55 with a history of cardiovascular disease; However,
these would constitute three different high risk subgroups. The subgroup analysis will define these
subgroups based on a data-driven approaches which may include cluster-analysis type methods to assign
individuals to mutually exclusive risk groups, decision-tree based methods that prioritize maximally
informative variables and apply these in nested sequences, or dimensionality reduction methods such as
principal component analyses that map all individuals along a reduced set of orthogonal risk axes.
The output of these analyses will serve as input to DP-Next WP 4, by defining high risk subgroups
that can be defined operationally with relative ease. One or two of these subgroups will form the
target populations for the process of participative intervention development described in WP4

*** Individuals
In Denmark, based on matching data availability between the DST and EMR data environments, a suitable
model from the population focused analyses will be selected for transfer to the EMR environment
(e.g. family history or SES data may not be available in the EMR environment). The prediction model
will be transferred and its performance will be validated in a closed, older extract of data
(e.g. with a 5-year follow-up horizon for incident diabetes). Subsequently, the added predictive
value of a restricted set of additional variables that may be available in the EMR but not the DST
environment will be assessed (e.g. BMI). Analyses will focus on quantifying the predicted risk of
diabetes from the point of view of an individual and their physician. This means that beside the
over-all risk estimate, an individual breakdown of the proportion of that risk explained by the
various risk indicators should be calculated; subdivided by modifiable and unmodifiable risk factors.
This may require a re-analysis based on an underlying aetiological model rather than a simply
predictive model, in order to allow estimates to be used in counterfactual scenarios used in planning
a clinical course of action. E.g: Your calculated 5-year risk is currently 6%. If we manage to reduce
your weight by 2kg and your HbA1c by 1 mmol/mol, your risk would be reduced to 5%.

*** The Health System
After validation of the individual EMR based models, predicted diabetes risk estimates will be
calculated based on the most up-to-date data for individuals attending a few selected clinical
settings (e.g. a few selected GP practices) in order to evaluate how individuals and health care
practitioners understand and interpret the data and to make an initial assessment of how these
individual risk estimates may be incorporated into the day to day data flow of a practice. Finally,
the possibilities for integrating the individual-level predicted risk data into the SAMBLIK system
will be explored and piloted.


** Work flow
We will build upon our own methodology framework, experience and paradigms for making medical risk prediction models [cite:@vistisen2016prediction], [cite:@wright2021] [cite:@gerds2021medical], [cite:@liu2024predicting]. We will develop a lego system of learners (parametric models and machine 
learning) which provides a super learner algorithm [cite:@super] for prediction. The super learner algorithm can be applied to (a subset of) the current data. It uses nested cross-validation to return the best risk prediction model according to current constraints and outperforms all benchmark models.

*** Danish registers 
- CPR Register [1968-]
- LPR (Danish National Patient Registry) [1977-]
- LMDB (Danish National Prescription Registry) and the Hospital Medication Register [1995-]
- Register of Laboratory Results for Research [2011/2015Q4-]
- Cancer Register [1987-]
- Pathology Register [1997-]
- Diabase (RKKP) [2013-]
- RKKP (Danish Registry of Diabetes) [2022Q3-]
- Health Insurance [1990-]
- Medical Birth Register [1973-]
- DREAM database [1991-/2008-]
- HANDIC Register [2013-/2018-]
- FAIK/register of incomes [1990-]
- Vaccination Register [2013-/2016-]



\newpage
* Bibliography
#+print_bibliography:
