#+TITLE: PhD Thesis
#+Author: Hjalte Søberg Mikkelsen
#+Date: 
#+EMAIL: hjalte.soeberg.mikkelsen@regionh.dk
#+LaTeX_CLASS: org-article 
#+OPTIONS: toc:nil
#+LaTeX_HEADER:\usepackage{authblk}
#+LaTeX_HEADER:\author{Hjalte Søberg Mikkelsen}
#+LaTeX_HEADER:\affil{Steno Diabetes Center Copenhagen}
#+setupfile:~/emacs-genome/snps/org-templates/setup-all-purpose.org
# #+superman-org-export-target: pdf
#+BIBLIOGRAPHY: bibliography.bib
#+cite_export: csl ~/emacs/.csl-styles/apa.csl

* Demography and epidemiologi

** Incidence rate

Rate

*** Standardization

age


** Lifetable analysis
A lifetable describes how a hypothetical closed birth cohort reduces with rising age alone because of death. The cohort is fictional and consists of \ell_0 persons, where it is assumed all people are born at the same time. \ell_0 is called radix and is usually set to 100.000 people. The function \ell_x ($l$ is used in the examples below) tells us how many people are still alive at the age $x$, and describes how the table-population declines because of death. As the cohort is closed it must be true that \ell_x\geq \ell_{x+1}. In the lifetable $x$ is the start of the age interval.\\

Example of a lifetable
#+begin_example
# A tibble: 11 × 9
   Alder      l     d     p        q     o      L        T     e
   <fct>  <dbl> <dbl> <dbl>    <dbl> <dbl>  <dbl>    <dbl> <dbl>
 1 0     100000   251 0.997 0.00251  1      99774 8334430. 83.3 
 2 1-9    99749    80 0.999 0.000799 0.997 897385 8234656. 82.6 
 3 10-19  99670    96 0.999 0.000963 0.997 996216 7337271. 73.6 
 4 20-29  99574   189 0.998 0.00190  0.996 994789 6341056. 63.7 
 5 30-39  99384   377 0.996 0.00380  0.994 991955 5346266. 53.8 
 6 40-49  99007   890 0.991 0.00899  0.990 985620 4354311. 44.0 
 7 50-59  98117  2821 0.971 0.0288   0.981 967065 3368691. 34.3 
 8 60-69  95296  7751 0.919 0.0813   0.953 914204 2401626. 25.2 
 9 70-79  87545 16278 0.814 0.186    0.875 794062 1487422. 17.0 
10 80-89  71267 36296 0.491 0.509    0.713 531192  693360.  9.73
11 90+    34971 34971 0     1        0.350 162168  162168.  4.64
#+end_example

#+Label: tab:lifetable-columns
#+CAPTION: Explanation of the columns in a lifetable
#+ATTR_LATEX: :align l|l
| Column  | Meaning  |
|----------+----------|
| Age | Age-interval |
| l | Decrement function: Number of table persons in the start of the interval |
| d | Number of deaths in the interval |
| p | Probability of surviving in the inteval given being alive at the start  |
| q | Probability of dying in the interal given being alive at the start |
| o | Probability of having survived up until the start |
| L | Total risktime in the interval |
| T | Total liftime from the start of the interval |
| e | Average rest lifetime |

From the lifetable example we can see, under the assumption that the mortality rates won't change, that a newborn baby will be expected to live for 83.3 years, and that a 50 year old would be expected to live for another 34.3 years.
#+begin_export latex
\begin{align*}
o_x= \frac{\ell_{x}}{\ell_0}
\end{align*}
#+end_export

$_kq_x$ is the probabilty for a person at the age $x$ of dying before the age $x+k$. To approximate this probability we use the formular:
#+begin_export latex 
\begin{equation}\label{k3-dhyppig}
_kq_x= \frac{k\cdot {_kM_x}}{1+(k-{_ka_x})\cdot {_kM_x}}.
\end{equation}
#+end_export
This formular depends on the age specific mortality rates $_kM_x$, the length of the age interval $k$ and Chiangs $a$, $_ka_x$. $_ka_x$ describes the average lifetime in the age interval for the persons who died in between the ages $x$ and $x+k-1$. This is usually set to the middle of the interval, i.e. $_10_a_50 = 5$. This assumes that the risk of dying in the interval is the same across the ages. This is usually not the case in the first interval and the last.\\
The central formular can be rewritten to:
#+begin_export latex
\begin{align*}
\frac{k\cdot {_kM_x}}{1+(k-{_ka_x})\cdot {_kM_x}} = \frac{k\cdot {_kD_x}}{_kR_x+(k-{_ka_x})\cdot {_kD_x}}
\end{align*}
#+end_export
where $_kR_x$ is ... and $_kD_x$ is ...

#+begin_export latex
\begin{align*}
_kd_x = {_kq_x}\cdot \ell_x.
\end{align*}
#+end_export
#+begin_export latex
\begin{align*}
\ell_{x+k} = \ell_x-{_kd_x}.
\end{align*}
#+end_export
#+begin_export latex
\begin{align*}
\ell_{x+k} = \ell_x(1-{_kq_x}).
\end{align*}
#+end_export
#+begin_export latex
\begin{align*}
_kd_x = \ell_x-\ell_{x+k}.
\end{align*}
#+end_export



* Survival Analysis

** Cox model

*** Breslow Estimator

*** Parametric
