#+TITLE: Constrained Risk Prediction
#+Author: Hjalte Søberg Mikkelsen
#+Date: 
#+EMAIL: hjalte.soeberg.mikkelsen@regionh.dk
#+LaTeX_CLASS: org-article 
#+OPTIONS: toc:nil
#+LaTeX_HEADER:\usepackage{authblk}
#+LaTeX_HEADER:\author{Hjalte Søberg Mikkelsen}
#+LaTeX_HEADER:\affil{Steno Diabetes Center Copenhagen}
#+setupfile:~/emacs-genome/snps/org-templates/setup-all-purpose.org
# #+superman-org-export-target: pdf
#+BIBLIOGRAPHY: bibliography.bib
#+cite_export: csl ~/emacs/.csl-styles/apa.csl
\newpage

* Introduction

Accurate prediction of disease risk in the presence of competing risks remains a central challenge in clinical epidemiology. We target individualized predictions of the 5-year risk of type 2 diabetes (T2D) and simultaneously the 5-year risk of the competing risk of death. Common estimation methods, such as Fine-Gray regression and cause-specific Cox regression, target only one cause at a time and are not optimized for a given prediction time horizon.
We develop a loss-based estimation framework for the simultaneous prediction of multiple competing risks at a prespecified time horizon. Our approach provides a way to estimate a broad class of existing regression models for competing risks such that the resulting models are optimized for individualized risk prediction. Crucially, the framework enables seamless integration of flexible learner libraries and enables structural constraints during estimation. These may include coherence constraints that guarantee that the predicted risks respect the parameter space and domain-informed shape constraints (e.g., monotonicity in age). Estimation is achieved via constrained optimization of a differentiable loss function, such as the Brier score.


* The Problem

Assume we want to predict the risk of diabetes and the risk of death at some timepoint $\tau$, i.e. we want to predict the risk of each cause in a competing risks scenario. Denote $T$ as the time between time0 and the date of an event and $D\in\{0,1,...,K\}$ as the cause of the event, where $D = 0$ is censoring. Let $X = (X^1,...,X^p)$ be a p-dimensional vector of baseline covariates, which can both be numeric or categorical.\\
Consider a setting where $D\in\{0,1,2\}$ and $X$ is 1-dimensional. Define the cumulative hazard for $D = j$ as
#+begin_export latex
\begin{align*}
\Lambda_j(t|x) = \exp(x\beta_j)\Lambda_{0j}(t)
\end{align*}
#+end_export
where $\Lambda_{0j}$ is the baseline cumulative hazard for cause j, which is defined as $\Lambda_{0j}(t) = \int_0^t \lambda_{0j}(s)ds$, where $\lambda_{0j}$ is the baseline hazard. The baseline hazard is however not estimated when fitting a cause-specific cox model. Now define the survival function using the product integral as
#+begin_export latex
\begin{align*}
S(t|x) = \prod_{s \leq t}\left(1-d\Lambda_1(s|x)-d\Lambda_2(s|x)\right),
\end{align*}
#+end_export
or using the exponential approximation
#+begin_export latex
\begin{align*}
S(t|x) = \exp(-\Lambda_1(t|x)-\Lambda_2(t|x)).
\end{align*}
#+end_export
We can then write the cumulative incidence function for cause $j$, $F_j(t|x) = P(T\leq t, D = j|X)$, as
#+begin_export latex
\begin{align*}
F_j(t|x) = \int_0^t S(s-|x)d\Lambda_j(s|x).
\end{align*}
#+end_export
The problem I will look at is that current methods of estimation of the cause-specific risks estimates the cause-specific cumulative incidence functions seperately. The problem with this is that it can lead to wrong estimations, which can easily be verified as it can happen that for $\tau$ and some $x^*$
#+begin_export latex
\begin{align}
F_1(\tau|x^*)+F_2(\tau|x^*)>1.
\end{align}
#+end_export
I will in this project develope a method to estimate the risks simultaniously such that the above can't happen. MAYBE ALSO MENTION THE PROPORTIONAL HAZARDS ASSUMPTION, AND THAT BY USING BRIER-SCORE AS ESTIMATOR WE DON'T NEED THAT ASSUMPTION AS WE OPTIMIZE THE PARAMETERS FOR A GIVEN \tau, AND DONT OPTIMIZE FOR THE WHOLE TIME PERIOD. Maybe this should also be the new goal instead of the "estimation of all causes simultaniously" goal. i.e. "In this project we aim to develope an estimation method based on the proportional hazards model that do not need the proportional hazards assumption". This is interresting as the proportional hazards model is so popular and being able to still use it while having an assumption less is huge.  


* Different loss functions

** Likelihood function
Asume we have $N$ datapoints and $K$ different causes. The general parametric likelihood function in a competing risks setting can be written as:
#+begin_export latex
\begin{align*}
L = \prod_{i = 1}^N\lambda_{j_i}(t_i|x_i)^{d_i}S(t_i|x_i),
\end{align*}
#+end_export
where $d_i$ is 1 if an event was observed and 0 if $i$ is censored, and $j_i$ is which event occured for person $i$. Using that the survival function is a product of the individual cause-specific survival functions, $S(t_i|x_i) = \prod S_j(t_i|x_i)$, we can write the likelihood as:
#+begin_export latex
\begin{align*}
L &= \prod_{i = 1}^N\lambda_{j_i}(t_i|x_i)^{d_i}\prod_{j = 1}^K\exp(-\Lambda_j(t_i|x_i))\\
&= \prod_{i = 1}^N\prod_{j = 1}^K\lambda_{j_i}(t_i|x_i)^{d_{ij}}\exp(-\Lambda_j(t_i|x_i)).
\end{align*}
#+end_export
This means that the likelihood function is a product of K likelihoods, one for each cause. We can then maximize this likelihood by maximizing each cause-specific likelihood function, as long as the parameters are different for each cause.

*** Likelihood estimating equations
Assume two causes, only one covariate and constant baseline hazards. I then differentiate the log-likelihood functions with respect to the parameters. The negative log-likelihood function for cause $j$ is then:
#+begin_export latex
\begin{align*}
-\log(L_j) = \sum_{i = 1}^N-d_{ij}(\beta_jx_i+\log(\lambda_{0j}))+t_i\exp(\beta_jx_i)\lambda_{0j}
\end{align*}
#+end_export
and differentiated
#+begin_export latex
\begin{align*}
\frac{d-\log(L_j)}{d\beta_j} = \sum_{i = 1}^N-d_{ij}x_i+t_ix_i\exp(\beta_jx_i)\lambda_{0j}
\end{align*}
#+end_export
#+begin_export latex
\begin{align*}
\frac{d-\log(L_j)}{d\lambda_{0j}} = \sum_{i = 1}^N-\frac{d_{ij}}{\lambda_{0j}}+t_i\exp(\beta_jx_i)
\end{align*}
#+end_export


** Brier score
As our target in risk prediction is to minimize the Brier-score, it makes sense to fit the models by choosing the parameters which minimizes the brier-score. By using the Brier-score as our loss function, we also optimize our parametres based on a single timepoint (the prediction horizon), which is of great interrest in risk prediction. The model produced by minimizng the Brier-score will also be fully parametric, which will allows us to easily used it outside of online enviroments like DST.
\\
Assuming we have $N$ datapoints of the form $(\tilde{T},\tilde{D},X)$ where $\tilde{T}\in (0,\infty)$ is the observed time (time to first observed event), $\tilde{D}\in\{1,2,...,k\}$ is the observed event and $X$ is a p-dimensional covariate vector. The Brier-Score for predicting cause $j$ at timepoint $\tau$ can be written as
#+begin_export latex
\begin{align*}
BS = \frac{1}{N}\sum_{i = 1}^N(F_j(\tau|x_i)-o_i(\tau,j))^2,
\end{align*}
#+end_export
where $o_i(\tau,j)$ is the true outcome of person $i$, i.e. $o_i(\tau,j) = 1(\tilde{D}_i= j,\tilde{T}_i\leq \tau)$. Assume $K$ different causes and assume no censoring (with censoring just add a 0 state such that we have $K+1$ states and the setup will be similar to that of the joint survival super learner). We then want to find the parameters that minimize the Brier-score or all causes i.e.
#+begin_export latex
\begin{align*}
BSS = &\arg\min_{\boldsymbol{\beta}\in\mathbb{R},\boldsymbol{\Lambda_0}\in\mathbb{R}^+}\sum_{j = 1}^K\frac{1}{N}\sum_{i = 1}^N(F_j(\tau|x_i,\boldsymbol{\beta},\boldsymbol{\Lambda_0})-o_i(\tau,j))^2\\
= &\arg\min_{\boldsymbol{\beta}\in\mathbb{R},\boldsymbol{\Lambda_0}\in\mathbb{R}^+}\frac{1}{N}\sum_{j = 1}^K\sum_{i = 1}^N\left(\int_0^{\tau} S(s-|x_i,\boldsymbol{\beta},\boldsymbol{\Lambda_0})d\Lambda_j(s|x_i,\boldsymbol{\beta}_j,\Lambda_{0j})-o_i(\tau,j)\right)^2,
\end{align*}
#+end_export
where $\boldsymbol{\beta}$ are the beta coeffecients for all causes and $\boldsymbol{\Lambda_0}$ are the baseline hazards, with j indicating the coeffecients for the specific cause. BSS = Brier-score-sum. This is actually just the Brier-score as it was written by Brier in the orginal paper. 



*** Find estimating equations in Parametric Cox with exponential baseline hazard
Assume we are in a competing risks setting with two causes and one covariate $x$, and we are interrested in predicting the risk of experiencing the events before or at timepoint $\tau$ using a cox model and let $\phi = \{\beta_1,\beta_2,\Lambda_{01},\Lambda_{02}\}$. First we take the simpler example and use the exponential approximation of the survival function and assume a constant baseline hazard. The hazard for cause $j$ will the be
#+begin_export latex
\begin{align*}
\lambda_j = \exp(\beta_jx)\lambda_{0j},
\end{align*}
#+end_export
where $\lambda_{0j}$ is some constant. We are interested in solving this:
#+begin_export latex
\begin{align*}
BSS=\arg\min_{\beta_1,\beta2\in\mathbb{R},\lambda_{01},\lambda_{02}\in\mathbb{R}^+}\frac{1}{N}\sum_{j = 1}^2\sum_{i = 1}^N\left(g_j(\phi)-o_i(\tau,j)\right)^2.
\end{align*}
#+end_export
First I rewrite $g_1(\phi) = \int_0^{\tau} S(s-|x,\boldsymbol{\beta},\boldsymbol{\Lambda_0})\lambda_1(s|x,\boldsymbol{\beta}_1,\Lambda_{01})ds$ from the Brier-score written above (note that $g_1$ is equal to $F_1$ for a fixed timepoint $\tau$):
#+begin_export latex
\begin{align*}
g_1(\phi)&= \int_0^{\tau}\exp\left[-\exp(\beta_1x)\Lambda_{01}(s-)-\exp(\beta_2x)\Lambda_{02}(s-)\right]\exp(\beta_1x)\lambda_{01}ds\\
&=\exp(\beta_1x)\lambda_{01}\int_0^{\tau}\exp\left[-\exp(\beta_1x)s^-\lambda_{01}-\exp(\beta_2x)s^-\lambda_{02}\right]ds\\
&=\exp(\beta_1x)\lambda_{01}\frac{\exp\left[\tau^-(-\exp(\beta_1x)\lambda_{01}-\exp(\beta_2x)\lambda_{02})\right]-1}{-\exp(\beta_1x)\lambda_{01}-\exp(\beta_2x)\lambda_{02}}\\
&=\exp(\beta_1x)\lambda_{01}\frac{1-\exp\left[\tau^-(-\exp(\beta_1x)\lambda_{01}-\exp(\beta_2x)\lambda_{02})\right]}{\exp(\beta_1x)\lambda_{01}+\exp(\beta_2x)\lambda_{02}}
\end{align*}
#+end_export
As we are in continous time $\tau^-= \tau$. Then we differentiate $g_1$ with respect to $\beta_1$, $\beta_2$, $\lambda_{01}$ and $\lambda_{02}$ (to get the result for $g_2$ just swap all the 1's and 2's, also the ones on the left side of the equals sign):
#+begin_export latex
\begin{align*}
\frac{\partial g_1(\phi)}{\partial\beta_1} = &\frac{x \lambda_{01} e^{x \beta_1}}{\left(\lambda_{01} e^{x \beta_1} + \lambda_{02} e^{x \beta_2}\right)^2}\\
&\cdot\left[
\lambda_{02} e^{x \beta_2}\left(1 - e^{-\tau\left(\lambda_{01} e^{x \beta_1} + \lambda_{02} e^{x \beta_2}\right)}\right)
+ \tau \lambda_{01} e^{x \beta_1}\left(\lambda_{01} e^{x \beta_1} + \lambda_{02} e^{x \beta_2}\right)e^{-\tau\left(\lambda_{01} e^{x \beta_1} + \lambda_{02} e^{x \beta_2}\right)}
\right]
\end{align*}
#+end_export
#+begin_export latex
\begin{align*}
\frac{\partial g_1(\phi)}{\partial\beta_2} =\frac{xe^{\beta_1x}\lambda_{01}e^{\beta_2x}\lambda_{02}}{(e^{\beta_1x}\lambda_{01}+e^{\beta_2x}\lambda_{02})^2}\left[(1+\tau(e^{\beta_1x}\lambda_{01}+e^{\beta_2x}\lambda_{02}))e^{-(e^{\beta_1x}\lambda_{01}+e^{\beta_2x}\lambda_{02})\tau}-1\right]
\end{align*}
#+end_export
#+begin_export latex
\begin{align*}
&\frac{\partial g_1(\phi)}{\partial \lambda_{01}}
=\frac{e^{\beta_1 x}}{\left(e^{\beta_1 x}\lambda_{01}+e^{\beta_2 x}\lambda_{02}\right)^2}\\
&\cdot\left[e^{\beta_2 x}\lambda_{02}\left(1-e^{-\tau\left(e^{\beta_1 x}\lambda_{01}+e^{\beta_2 x}\lambda_{02}\right)}\right)+\tau e^{\beta_1x}\lambda_{01}\left(e^{\beta_1 x}\lambda_{01}+e^{\beta_2 x}\lambda_{02}\right)e^{-\tau\left(e^{\beta_1 x}\lambda_{01}+e^{\beta_2 x}\lambda_{02}\right)}\right]
\end{align*}
#+end_export
#+begin_export latex
\begin{align*}
\frac{\partial g_1(\phi)}{\partial\lambda_{02}} = \frac{e^{\beta_1x}\lambda_{01}e^{\beta_2x}}{(e^{\beta_1x}\lambda_{01}+e^{\beta_2x}\lambda_{02})^2}\left[(1+\tau(e^{\beta_1x}\lambda_{01}+e^{\beta_2x}\lambda_{02}))e^{-(e^{\beta_1x}\lambda_{01}+e^{\beta_2x}\lambda_{02})\tau}-1\right]
\end{align*}
#+end_export
Using this we can now differentiate the Brier-Score (BS) with respect to the betas to get the estimating equations:
#+begin_export latex
\begin{align*}
\frac{\partial BSS(\phi)}{\partial\beta_1} &=\frac{1}{N}\sum_{j = 1}^K\sum_{i = 1}^N \frac{dg_j(\phi)}{\beta_1}2(g_j(\phi)-o_i(t,j))\\
&= 0
\end{align*}
#+end_export
#+begin_export latex
\begin{align*}
\frac{\partial BSS(\phi)}{\partial\beta_2} &=\frac{1}{N}\sum_{j = 1}^K\sum_{i = 1}^N \frac{dg_j(\phi)}{\beta_2}2(g_j(\phi)-o_i(t,j))\\
&= 0
\end{align*}
#+end_export
#+begin_export latex
\begin{align*}
\frac{\partial BSS(\phi)}{\partial\lambda_{01}} &=\frac{1}{N}\sum_{j = 1}^K\sum_{i = 1}^N \frac{dg_j(\phi)}{\lambda_{01}}2(g_j(\phi)-o_i(t,j))\\
&= 0
\end{align*}
#+end_export
#+begin_export latex
\begin{align*}
\frac{\partial BSS(\phi)}{\partial\lambda_{02}} &=\frac{1}{N}\sum_{j = 1}^K\sum_{i = 1}^N \frac{dg_j(\phi)}{\lambda_{02}}2(g_j(\phi)-o_i(t,j))\\
&= 0
\end{align*}
#+end_export
Note that the $\frac{1}{N}$ terms can be removed.


*** COMMENT Using Cox-Weibull
The hazard function for the Cox-Weibull model for cause j is
#+begin_export latex
\begin{align*}
\h_j(t|x) = \lambda_j\exp(\beta_jx)v_jt^{v_j-1},
\end{align*}
#+end_export
where $\lambda_j>0$ is the scale parameter and $v_j>0$ is the shape parameter. The baseline hazard is
#+begin_export latex
\begin{align*}
h_{0,j}(t) = \lambda_jv_jt^{v_j-1},
\end{align*}
#+end_export
and the cumulative baseline hazard function is
#+begin_export latex
\begin{align*}
H_{0,j}(t) = \lambda_jt^{v_j}.
\end{align*}
#+end_export
This means the survival function will be
#+begin_export latex
\begin{align*}
S(t|x) = \exp(-(\exp(\beta_1x)\lambda_1t^{v_1}+\exp(\beta_2x)\lambda_2t^{v_2})),
\end{align*}
#+end_export
and the cumulative incidence function for cause 1 is
#+begin_export latex
\begin{align*}
F_1(t|x)
&= \int_0^t\exp(-(\exp(\beta_1x)\lambda_1s^{v_1}+\exp(\beta_2x)\lambda_2s^{v_2}))\lambda_1\exp(\beta_1x)v_1s^{v_1-1}ds.
\end{align*}
#+end_export
The cumulative incidence function does not have a closed form, so it needs to be numerical approximated in practise.

* Estimation with constraint

Assuming we have $N$ datapoints, the Brier-Score for predicting cause $j$ at timepoint $\tau$ can be written as
#+begin_export latex
\begin{align*}
BS_j = \frac{1}{N}\sum_{i = 1}^N(F_j(\tau|x_i)-o_i(\tau,j))^2,
\end{align*}
#+end_export
where $o_i(\tau,j)$ is the true outcome of person $i$ (1 if event j is the observed event and has happened at or before timepoint t and 0 otherwise). Furthermore assume only two competing risks (T2D and death). We then want to find the parameters that minimize this score i.e.
#+begin_export latex
\begin{align*}
&\arg\min_{\boldsymbol{\beta}\in\mathbb{R}}\sum_{j = 0}^K\frac{1}{N}\sum_{i = 1}^N(F_j(\tau|x_i,\boldsymbol{\beta})-o_i(\tau,j))^2.
\end{align*}
#+end_export
In our setting $K = 2$ where $j = 0$ is the censored state and 1 and 2 are T2D and death. We need to minimize this score under some constraint, for example:
#+begin_export latex
\begin{align*}
\sum_{j = 0}^K F_j(\tau|x,\boldsymbol{\beta})\leq 1 \text{ for all x},
\end{align*}
#+end_export
or
#+begin_export latex
\begin{align*}
\frac{d}{d\beta_{age}}F_j(\tau|x_i,\boldsymbol{\beta})>0
\end{align*}
#+end_export
for some $j$. In the T2D and death example $j\in\{1,2\}$, as those risks should increase with age. In practise in may be easier to rewrite the minimization problem to:
#+begin_export latex
\begin{align*}
&\arg\min_{\boldsymbol{\beta}\in\mathbb{R}}\sum_{j = 0}^K\frac{1}{N}\sum_{i = 1}^N(F_j(\tau|x_i,\boldsymbol{\beta})-o_i(\tau,j))^2+ I\left(\frac{d}{d\beta_{age}}F_j(\tau|x_i,\boldsymbol{\beta})\leq0\right),
\end{align*}
#+end_export
i.e. add the constraint to the loss function as a new term which will be 0 if the constraint holds and 1 otherwise which is large as we are using the Brier-score. We should probably multiply the indicator function with $K+1$, as we sum $K+1$ Brier-scores. \\
If we want methods like Newton-Raphson to work we probably need to use a different method as above, as the loss-function need to be smooth. Say we have the constraint $g(\beta)\leq 0$ then we can use the loss function:
#+begin_export latex
\begin{align*}
&\arg\min_{\boldsymbol{\beta}\in\mathbb{R}}\sum_{j = 0}^K\frac{1}{N}\sum_{i = 1}^N(F_j(\tau|x_i,\boldsymbol{\beta})-o_i(\tau,j))^2+\lambda\max(0,g(\beta))
\end{align*}
#+end_export
where $\lambda$ is some penalization parameter. 

* COMMENT Non-convexity of BSS
The BSS can be shown to be non-convex...

A function $f$ is convex if for any two points $x$ and $y$ in its domain and $\lambda\in[0,1]$ the following holds:
#+begin_export latex
\begin{align*}
f(\lambda x+(1-\lambda)y)\leq \lambda f(x)+(1-\lambda)f(y).
\end{align*}
#+end_export
A convex functions second derivative must be non-negative across the entire domain, so it can be shown that a non-convex function will have atleast 1 point where
#+begin_export latex
\begin{align*}
f''(x)<0.
\end{align*}
#+end_export


#+begin_export latex
\begin{align*}
f(\boldsymbol{\beta},\boldsymbol{\Lambda_0}) = &\sum_{j = 1}^K\frac{1}{N}\sum_{i = 1}^N(F_j(\tau|x_i,\boldsymbol{\beta},\boldsymbol{\Lambda_0})-o_i(\tau,j))^2\\
= &\frac{1}{N}\sum_{j = 1}^K\sum_{i = 1}^N\left(\int_0^{\tau} S(s-|x_i,\boldsymbol{\beta},\boldsymbol{\Lambda_0})d\Lambda_j(s|x_i,\boldsymbol{\beta}_j,\Lambda_{0j})-o_i(\tau,j)\right)^2,
\end{align*}
#+end_export


* Censoring
The BSS handles censoring well as is, and outperforms everything in the simulation study. Why?


* Simulation study

We want to test our method in four different setups: first where the model is correctly specified, second where the model is not correctly specified but still proportional hazards and one where the proportional hazards assumption doesnt hold. This is done by simulating data from parametric Cox models, with different baseline hazards: first it will be exponentially distributed, second it will be Weibull distributed, and lastly it will be Weibull where the shape parameter will depend on covariates. This will be done both with and without censoring, where the censoring process is Cox-weibull. In all the simulations the models will be fitted using 70 percent of the data, and evaluated by calculating the BSS on the 30 percent of data not used for training.

We test our estimation method against the exponential-Cox model estimated using maximum likelihood, the logistic regression model and the standard Cox proportional hazards model.

** Correctly specified model (Sim-setup 1)
In this setup we are interrested in two things: See if our method finds the true parameters and compare model performance between BSE and other models. The results of these simlation studies can found in the simulation_study folder in the targets: does_BS_find_correct_pars, simulation_cox_exp, simulation_cox_exp_cens.

Brier-score estimation does indeed find the data-generating parameters, but can fail if the starting parameters are chosen poorly. When data contains no censoring all the methods perform approximately the same, with the Oracle estimator performing best and the BSE performing worst. The models also perform almost equal when about 30 percent of the data is right censored, but here the BSE performs best and the logistic model perfroms worst.

** Not correctly specified (Sim-setup 2)
All the methods perform approximately the same when there is no censoring in the data. When introducing censoring the BSE outperforms the rest.


** Non-proptional hazards model (Sim-setup 3)
When data violates the proportional hazards assumption the BSE outperforms all the other methods, both when data contains censoring and when no censoring is occuring.


** Choosing starting parameters

The optimal way to choose starting parameters for the optimizer would be to try many different values for each parameter and choose the best outcome. However this is computational heavy and time comesuming. A good way to choose starting parameters I have found is to use the parameters from a fitted Cox model. Note that we can never be sure if we have found the true minimum of the BSS.


* "Real" data example
Here we test our method on synthetic data that mimics the data used for the Steno1-risk-engine (USE DATA FROM DP-NEXT INSTEAD), and show the performance against the Cox-proportional hazards model. 














